const formOpenBtn = document.querySelector("#form_open"),
    home1 = document.querySelector(".home1") ,
    formContainer = document.querySelector(".form_container"),
    formCloseBtn = document.querySelector(".form_close"),
    loginBtn = document.querySelector("#signup"),
    signupBtn = document.querySelector("#signup"),
    pwShowHide = document.querySelectorAll(".pw_hide"),

    formOpenBtn = .addEventListener("click", () => home1.classList.add("show")),
    formCloseBtn = .addEventListener("click", () => home1.classList.remove("show")),